##test_base directory
test_base_dir : '/u01/app/tests/test_base_dir'

wls_test_results_ctl: "{{ test_base_dir }}/results"

buildout_ctl: "{{ test_base_dir }}/build_out"

odx_wlstest_zip_download_url: 'https://objectstorage.us-phoenix-1.oraclecloud.com/p/hQPivxOwq3hJmPOeprgjQSnACZtFABQ9iqsJJVHiKc_8e0YZWUOCTgJbM-jeeeez/n/odx-pre-customer/b/myBucket/o/wlstest.zip'

global_lb_ip: "{{ hostvars[groups['loadbalancer_vm'][0]]['inventory_hostname'] }}"
