- name: Configure Dynamic Cluster Domain
  hosts:  admin_vm,managed_server_vms
  become: true
  gather_facts: true
  vars_files:
    - global-vars.yml
    - secrets.yml
  roles:
    - role: basic-setup
      when: basic_setup | bool
    - role: install-jdk
      when: install_jdk | bool
    - role: install-wls
      when: install_wls | bool
    - role: wls-dynamic-cluster-domain
