- name: Configure Global Load Balancer
  hosts:  loadbalancer_vm
  become: true
  vars_files:
    - global-vars.yml
    - secrets.yml
  roles:
    - role: basic-setup
    - role: install-jdk
    - role: install-wls
    - role: setup-global-lb
